import { Box, Container, Divider, Grid, Typography } from "@mui/joy";
import NoteCard from "@/components/NoteCard";
import Head from "next/head";
import Header from "@/components/Header";
import { useNoteContext } from "@/contexts/NoteContext";
import { useAccount } from "wagmi";
import { useEffect, useState } from "react";

export default function Home() {
  const { notes } = useNoteContext();
  const [isConnected, setisConnected] = useState(false);
  const { isConnected: isWalletConnected } = useAccount();

  useEffect(() => {
    if (isWalletConnected) {
      setisConnected(true);
    } else {
      setisConnected(false);
    }
  }, [isWalletConnected]);

  return (
    <>
      <Container sx={{ pb: 4 }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Divider sx={{ my: 2 }} />
        {isConnected ? (
          <Grid
            container
            spacing={{ xs: 2 }}
            alignItems={"flex-start"}
            gridTemplateRows={"masonry"}
          >
            {notes.map(({ data, id }) => (
              <Grid key={id} xs={12} sm={6} md={4}>
                <NoteCard note={data} id={id} />
              </Grid>
            ))}
          </Grid>
        ) : (
          <Box>
            <Divider>
              <Typography
                level="body-md"
                sx={{
                  textAlign: "center",
                  my: 4,
                  color: "primary.500",
                }}
              >
                Kindly connect your wallet to fetch your notes
              </Typography>
            </Divider>
          </Box>
        )}
      </Container>
    </>
  );
}
